### ISSUE TITLE
执行不成功

### ISSUE THREAD

**Issue by maxiaoxian** [madaibaba/spark-on-yarn#2]
2019-07-24 09:32:58.328  INFO 912 --- [launcher-proc-1] org.apache.spark.launcher.app.hello      : Container exited with a non-zero exit code 13
2019-07-24 09:32:58.328  INFO 912 --- [launcher-proc-1] org.apache.spark.launcher.app.hello      : Failing this attempt. Failing the application.
2019-07-24 09:32:58.346  INFO 912 --- [launcher-proc-1] org.apache.spark.launcher.app.hello      : Exception in thread "main" org.apache.spark.SparkException: Application application_1563960561971_0001 finished with failed status
2019-07-24 09:32:58.347  INFO 912 --- [launcher-proc-1] org.apache.spark.launcher.app.hello      : 	at org.apache.spark.deploy.yarn.Client.run(Client.scala:1149)
2019-07-24 09:32:58.347  INFO 912 --- [launcher-proc-1] org.apache.spark.launcher.app.hello      : 	at org.apache.spark.deploy.yarn.YarnClusterApplication.start(Client.scala:1526)
2019-07-24 09:32:58.347  INFO 912 --- [launcher-proc-1] org.apache.spark.launcher.app.hello      : 	at org.apache.spark.deploy.SparkSubmit.org$apache$spark$deploy$SparkSubmit$$runMain(SparkSubmit.scala:849)
2019-07-24 09:32:58.348  INFO 912 --- [launcher-proc-1] org.apache.spark.launcher.app.hello      : 	at org.apache.spark.deploy.SparkSubmit.doRunMain$1(SparkSubmit.scala:167)
2019-07-24 09:32:58.361  INFO 912 --- [launcher-proc-1] org.apache.spark.launcher.app.hello      : 	at org.apache.spark.deploy.SparkSubmit.submit(SparkSubmit.scala:195)
2019-07-24 09:32:58.361  INFO 912 --- [launcher-proc-1] org.apache.spark.launcher.app.hello      : 	at org.apache.spark.deploy.SparkSubmit.doSubmit(SparkSubmit.scala:86)
2019-07-24 09:32:58.362  INFO 912 --- [launcher-proc-1] org.apache.spark.launcher.app.hello      : 	at org.apache.spark.deploy.SparkSubmit$$anon$2.doSubmit(SparkSubmit.scala:924)
2019-07-24 09:32:58.362  INFO 912 --- [launcher-proc-1] org.apache.spark.launcher.app.hello      : 	at org.apache.spark.deploy.SparkSubmit$.main(SparkSubmit.scala:933)
2019-07-24 09:32:58.362  INFO 912 --- [launcher-proc-1] org.apache.spark.launcher.app.hello      : 	at org.apache.spark.deploy.SparkSubmit.main(SparkSubmit.scala)
2019-07-24 09:32:58.404  INFO 912 --- [launcher-proc-1] org.apache.spark.launcher.app.hello      : 2019-07-24 09:32:58 INFO  ShutdownHookManager:54 - Shutdown hook called
2019-07-24 09:32:58.407  INFO 912 --- [launcher-proc-1] org.apache.spark.launcher.app.hello      : 2019-07-24 09:32:58 INFO  ShutdownHookManager:54 - Deleting directory /tmp/spark-4018fb8f-d11a-4f26-ba95-fab5bdae6cb8
2019-07-24 09:32:58.416  INFO 912 --- [launcher-proc-1] org.apache.spark.launcher.app.hello      : 2019-07-24 09:32:58 INFO  ShutdownHookManager:54 - Deleting directory /tmp/spark-6a7f6d57-dc8b-4a72-af30-3e806f5e12c8

**Comment by maxiaoxian** [comment]
能否给个示例

**Comment by madaibaba** [comment]
$ git clone https://github.com/madaibaba/spark-on-yarn
Cloning into 'spark-on-yarn'...
remote: Enumerating objects: 15, done.
remote: Counting objects: 100% (15/15), done.
remote: Compressing objects: 100% (12/12), done.
remote: Total 57 (delta 6), reused 11 (delta 3), pack-reused 42
Unpacking objects: 100% (57/57), done.

$ cd spark-on-yarn/

$ docker pull madaibaba/spark-on-yarn:2.0
2.0: Pulling from madaibaba/spark-on-yarn
18b8eb7e7f01: Pull complete 
7bc0865ab289: Pull complete 
7c9a1524ef04: Pull complete 
0a1d31df216e: Pull complete 
0d3433a7bd07: Pull complete 
79ea936da7fe: Pull complete 
732c00ff0d4f: Pull complete 
8312a0e99c4d: Pull complete 
63513b31d878: Pull complete 
f458c12f167f: Pull complete 
200b9ca2d538: Pull complete 
29ead68dbcce: Pull complete 
bf646d9cfb1a: Pull complete 
2a197c8b86be: Pull complete 
d44337c12e81: Pull complete 
36f9b7edf11b: Pull complete 
cf5ea7d7e805: Pull complete 
9db06389735a: Pull complete 
571da3908502: Pull complete 
8e00a49e76af: Pull complete 
Digest: sha256:7ab8cd8057fd448ddc4901eb5ee85996c234580d08df82ab3fa1bcffb203a9f5
Status: Downloaded newer image for madaibaba/spark-on-yarn:2.0
housong-saic:spark-on-yarn ykkqk$ docker network create -d bridge mybridge
127cd4d1ba4684cac85e15ebf488fe499251c049111bd5e43fee7963a76a6852

$ ./start-container.sh
The default node number is 3!
Password:
start hadoop-master container...
start hadoop-slave1 container...
start hadoop-slave2 container...


Starting namenodes on [hadoop-master]
hadoop-master: Warning: Permanently added 'hadoop-master,172.18.0.2' (RSA) to the list of known hosts.
hadoop-master: starting namenode, logging to /usr/local/hadoop/logs/hadoop-root-namenode-hadoop-master.out
hadoop-slave2: Warning: Permanently added 'hadoop-slave2,172.18.0.4' (RSA) to the list of known hosts.
hadoop-slave1: Warning: Permanently added 'hadoop-slave1,172.18.0.3' (RSA) to the list of known hosts.
hadoop-slave1: starting datanode, logging to /usr/local/hadoop/logs/hadoop-root-datanode-hadoop-slave1.out
hadoop-slave2: starting datanode, logging to /usr/local/hadoop/logs/hadoop-root-datanode-hadoop-slave2.out
Starting secondary namenodes [0.0.0.0]
0.0.0.0: Warning: Permanently added '0.0.0.0' (RSA) to the list of known hosts.
0.0.0.0: starting secondarynamenode, logging to /usr/local/hadoop/logs/hadoop-root-secondarynamenode-hadoop-master.out


starting yarn daemons
starting resourcemanager, logging to /usr/local/hadoop/logs/yarn--resourcemanager-hadoop-master.out
hadoop-slave1: Warning: Permanently added 'hadoop-slave1,172.18.0.3' (RSA) to the list of known hosts.
hadoop-slave2: Warning: Permanently added 'hadoop-slave2,172.18.0.4' (RSA) to the list of known hosts.
hadoop-slave2: starting nodemanager, logging to /usr/local/hadoop/logs/yarn-root-nodemanager-hadoop-slave2.out
hadoop-slave1: starting nodemanager, logging to /usr/local/hadoop/logs/yarn-root-nodemanager-hadoop-slave1.out

starting org.apache.spark.deploy.master.Master, logging to /usr/local/spark/logs/spark--org.apache.spark.deploy.master.Master-1-hadoop-master.out
hadoop-slave2: Warning: Permanently added 'hadoop-slave2,172.18.0.4' (RSA) to the list of known hosts.
hadoop-slave1: Warning: Permanently added 'hadoop-slave1,172.18.0.3' (RSA) to the list of known hosts.
hadoop-slave1: starting org.apache.spark.deploy.worker.Worker, logging to /usr/local/spark/logs/spark-root-org.apache.spark.deploy.worker.Worker-1-hadoop-slave1.out
hadoop-slave2: starting org.apache.spark.deploy.worker.Worker, logging to /usr/local/spark/logs/spark-root-org.apache.spark.deploy.worker.Worker-1-hadoop-slave2.out


[root@hadoop-master ~]# cat > /root/test.csv << EOF
> id,name,addr,oper,cdate
> 1,a,alex,i,2010-01-01 00:00:00
> 2,b,alex,i,2010-01-01 00:00:00
> 3,c,alex,i,2010-01-01 00:00:00
> 4,d,alex,i,2010-01-01 00:00:00
> 5,e,alex,i,2010-01-01 00:00:00
> 6,f,alex,i,2010-01-01 00:00:00
> 7,g,alex,i,2010-01-01 00:00:00
> 8,h,alex,i,2010-01-01 00:00:00
> 9,i,alex,i,2010-01-01 00:00:00
> 10,k,alex,i,2010-01-01 00:00:00
> EOF

[root@hadoop-master ~]# hdfs dfs -put /root/test.csv /tmp
[root@hadoop-master ~]# spark-shell
SLF4J: Class path contains multiple SLF4J bindings.
SLF4J: Found binding in [jar:file:/usr/local/spark/jars/slf4j-log4j12-1.7.16.jar!/org/slf4j/impl/StaticLoggerBinder.class]
SLF4J: Found binding in [jar:file:/usr/local/spark/jars/parquet-tools-1.10.0.jar!/org/slf4j/impl/StaticLoggerBinder.class]
SLF4J: Found binding in [jar:file:/usr/local/hadoop/share/hadoop/common/lib/slf4j-log4j12-1.7.10.jar!/org/slf4j/impl/StaticLoggerBinder.class]
SLF4J: See http://www.slf4j.org/codes.html#multiple_bindings for an explanation.
SLF4J: Actual binding is of type [org.slf4j.impl.Log4jLoggerFactory]
Warning: Master yarn-client is deprecated since 2.0. Please use master "yarn" with specified deploy mode instead.
2019-07-26 05:05:58 WARN  NativeCodeLoader:62 - Unable to load native-hadoop library for your platform... using builtin-java classes where applicable
Setting default log level to "WARN".
To adjust logging level use sc.setLogLevel(newLevel). For SparkR, use setLogLevel(newLevel).
2019-07-26 05:06:29 WARN  Client:66 - Neither spark.yarn.jars nor spark.yarn.archive is set, falling back to uploading libraries under SPARK_HOME.
Spark context Web UI available at http://hadoop-master:4040
Spark context available as 'sc' (master = yarn, app id = application_1564117489149_0001).
Spark session available as 'spark'.
Welcome to
      ____              __
     / __/__  ___ _____/ /__
    _\ \/ _ \/ _ `/ __/  '_/
   /___/ .__/\_,_/_/ /_/\_\   version 2.4.0
      /_/
         
Using Scala version 2.11.12 (OpenJDK 64-Bit Server VM, Java 1.8.0_191)
Type in expressions to have them evaluated.
Type :help for more information.

scala> val test = spark.read.option("header", "true").option("delimiter", ",").csv("hdfs://hadoop-master:9000/tmp/test.csv")
test: org.apache.spark.sql.DataFrame = [id: string, name: string ... 3 more fields]

scala> test.coalesce(2).write.parquet("hdfs://hadoop-master:9000/user/root/warehouse/test")
                                                                                
scala> val test = spark.read.parquet("hdfs://hadoop-master:9000/user/root/warehouse/test")
test: org.apache.spark.sql.DataFrame = [id: string, name: string ... 3 more fields]

scala> println(test.count)
10                                                                              

scala> test.show()
+---+----+----+----+-------------------+                                        
| id|name|addr|oper|              cdate|
+---+----+----+----+-------------------+
|  1|   a|alex|   i|2010-01-01 00:00:00|
|  2|   b|alex|   i|2010-01-01 00:00:00|
|  3|   c|alex|   i|2010-01-01 00:00:00|
|  4|   d|alex|   i|2010-01-01 00:00:00|
|  5|   e|alex|   i|2010-01-01 00:00:00|
|  6|   f|alex|   i|2010-01-01 00:00:00|
|  7|   g|alex|   i|2010-01-01 00:00:00|
|  8|   h|alex|   i|2010-01-01 00:00:00|
|  9|   i|alex|   i|2010-01-01 00:00:00|
| 10|   k|alex|   i|2010-01-01 00:00:00|
+---+----+----+----+-------------------+
